[package]
authors = ['J2ghz <j2.00ghz@gmail.com>']
edition = "2018"
license = 'AGPL-3.0'
name = "screeps"
version = "0.0.0"

[dependencies]
fern = "0.6"
log = "0.4"
screeps-game-api = "0.9.0"
stdweb = "0.4"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
panic = "abort"
