name: Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [1.47.0] #stable, beta, nightly]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          target: wasm32-unknown-unknown

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-screeps
          version: latest
          use-tool-cache: true

      - name: Build
        uses: actions-rs/cargo@v1.0.3
        with:
          command: screeps
          toolchain: ${{matrix.toolchain}}
          args: build
